version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend/
    ports:
      - 5050:5050
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src



volumes:
  mongodb_data:
    driver: local